# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o4wsd62uD_GWnbJ5V0JfojttRSSwU7q5
"""

import numpy as np
import matplotlib.pyplot as plt

x = np.linspace(-2 * np.pi, 2 * np.pi, 500)
y = np.sin(x)


plt.figure(figsize=(8, 6))
plt.plot(x, y, label='y = sin(x)', color='blue', linewidth=2)
plt.title("y = sin(x) Grafigi", fontsize=14)
plt.xlabel("x", fontsize=12)
plt.ylabel("y", fontsize=12)
plt.axhline(0, color='black', linewidth=0.5, linestyle='--')
plt.axvline(0, color='black', linewidth=0.5, linestyle='--')
plt.grid(color='gray', linestyle='--', linewidth=0.5)
plt.legend(fontsize=12)
plt.show()

import numpy as np
import matplotlib.pyplot as plt


num_points = 100
x = np.random.rand(num_points) * 10
y = np.random.rand(num_points) * 10


plt.figure(figsize=(8, 6))
plt.scatter(x, y, color='purple', alpha=0.7, edgecolors='black')
plt.title("Tasodifiy Nuqtalar Grafiki", fontsize=14)
plt.xlabel("X koordinatalari", fontsize=12)
plt.ylabel("Y koordinatalari", fontsize=12)
plt.grid(color='gray', linestyle='--', linewidth=0.5)
plt.show()

from PIL import Image


def convert_to_black_and_white(input_path, output_path):

    img = Image.open(input_path)

    bw_img = img.convert("L")

    bw_img.save(output_path)
    print(f"Oq-qora rasm saqlandi: {output_path}")


input_file = "1111.jpg"
output_file = "1111_bw.jpg"

convert_to_black_and_white(input_file, output_file)

import pandas as pd


data = {
    "Mamlakat": ["AQSh", "Hindiston", "Braziliya", "Rossiya", "Fransiya"],
    "Kasallar soni": [50000000, 35000000, 22000000, 19000000, 12000000],
    "Vafot etganlar": [800000, 500000, 600000, 400000, 200000],
    "Sog'ayganlar": [45000000, 32000000, 20000000, 17000000, 10000000]
}


df = pd.DataFrame(data)


def analyze_covid_data(df):
    print("1. COVID-19 bo'yicha jadval ma'lumotlari:")
    print(df, "\n")

    print("2. Umumiy kasallar soni:")
    print(df["Kasallar soni"].sum(), "\n")

    print("3. Umumiy vafot etganlar soni:")
    print(df["Vafot etganlar"].sum(), "\n")

    print("4. Umumiy sog'ayganlar soni:")
    print(df["Sog'ayganlar"].sum(), "\n")

    print("5. O'lim foizi (%):")
    df["O'lim foizi (%)"] = (df["Vafot etganlar"] / df["Kasallar soni"]) * 100
    print(df[["Mamlakat", "O'lim foizi (%)"]], "\n")

    print("6. Eng ko'p vafot etganlar qaysi mamlakatda:")
    max_deaths = df[df["Vafot etganlar"] == df["Vafot etganlar"].max()]
    print(max_deaths[["Mamlakat", "Vafot etganlar"]], "\n")

    print("7. Eng yuqori o'lim foizi qaysi mamlakatda:")
    max_death_rate = df[df["O'lim foizi (%)"] == df["O'lim foizi (%)"].max()]
    print(max_death_rate[["Mamlakat", "O'lim foizi (%)"]], "\n")


analyze_covid_data(df)